- dx-cluster-universal.yml
Tomcat was showing the value of `_JAVA_OPTIONS` when started in which some users and passwords was set.
Now the package do not use this envvar anymore and add options in `/opt/tomcat/conf/tomcat-env.sh`
> PAAS-150 no more passwords in catalina.out

- dx-cluster-universal.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-150
Nothing particular
> PAAS-150: restarting tomcat after copyapp during scaleout

- RELEASENOTES.md
- dx-cluster-universal.yml
- scripts/add-haproxies.jps
JIRA issue: https://jira.jahia.org/browse/PAAS-309
Linked to PR on paas_jelastic_dx
> Paas 309 haproxy

- RELEASENOTES.md
- utils/set-jahia-root-password.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-379
add new package to update jahia root password on an environment
> PAAS-379: add new package to update jahia root password

- RELEASENOTES.md
- scripts/reset-jahia-tools-manager-password.py
- utils/set-jahia-tools-password.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-381
add new package to update jahia tools password
> PAAS-381: add new package to update jahia tools password

- dx-cluster-universal.yml
- haproxy/add-haproxies.jps
JIRA issue: https://jira.jahia.org/browse/PAAS-413
Linked to PR on paas_jelastic_dx
> Paas 413 add productname haproxy

- dx-cluster-universal.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-410
> PAAS-410: rollback from jahia to dx

- configs/haproxy-00-global.cfg
- configs/haproxy-10-jahia.cfg
- haproxy/add-haproxies.jps
JIRA issue: https://jira.jahia.org/browse/PAAS-360
add haproxy config files and gzip compression in it
> PAAS-360: add haproxy config files and gzip compression in it

- dx-cluster-universal.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-376
disable mysql checks from ProxySQL
> PAAS-376: disable mysql checks from ProxySQL

- haproxy/add-haproxies.jps
JIRA issue: https://jira.jahia.org/browse/PAAS-371
enable sudo in haproxy
> PAAS-371: enable sudo in haproxy

- dx-cluster-universal.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-342
set cloudlets without node restart using js for node definition
> PAAS-342: set cloudlets without node restart

- dx-cluster-universal.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-294
- now using single docker image.
- docker image can be passed as a parameter in dx-universal
> Paas 294 jahia docker image parameter

- dx-cluster-universal.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-443
now using jahia/jahiastic-jahia docker images
> PAAS-443: now using jahia/jahiastic-jahia docker images

- dx-cluster-universal.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-552
Short description: add dbnodes default value
> PAAS-552: add dbnodes default value

- dx-cluster-universal.yml
…ter-universal package
JIRA issue: https://jira.jahia.org/browse/PAAS-NINJA
ninja commit to remove useless and confusing db topologies in dx-clus ter-universal package
> ninja commit to remove useless and confusing db topologies in dx-clus ter-universal package

- utils/onAfterClone.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-480
Fix bug in env clone
> Paas-480: Fix bug in env clone

- install.yml
- jahia/jahia_actions.yml
- upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-564
> Paas 564 cant redeploy or scale

- dx-upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-524
restore dx-upgrade.yml
> PAAS-524: restore dx-upgrade.yml

- jahia/jahia_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-564
> Paas 564 fix redeploy

- utils/onAfterClone.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-503
regen ssh keys after clone
> PAAS-503: regen ssh keys after clone

- configs/haproxy-00-global.cfg
- scripts/set-rewrite-rules.py
- utils/rewrite-rules.yml
> PAAS-401: haproxy rewrite rules

- install.yml
- jahia/jahia_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-531
Short description: always install datadog
> PAAS-531: always install datadog

- install.yml
- jahia/jahia_actions.yml
- upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-527
Remove jahia root and tools passwords from env vars
> PAAS-527: Remove jahia root and tools passwords from env vars

- configs/haproxy-00-global.cfg
- haproxy/haproxy_actions.yml
- scripts/manage-auth-basic.py
- utils/manage-auth-basic.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-403
add auth-basic on haproxy
> PAAS-403: add auth-basic on haproxy

- install.yml
- jahia/jahia_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-583
stop tomcat before env stop
> PAAS-583: stop tomcat before env stop

- jahia/jahia_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-519
add x-forwarded-proto in tomcat conf
> PAAS-519: add x-forwarded-proto in tomcat conf

- install.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-589
mysql nodes recovery in proxysql after env start
> PAAS-589: mysql nodes recovery in proxysql after env start

- utils/set-jahia-tools-password.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-606
> PAAS-606: Fix tools password update

- install.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-601
> Paas 601 rename dxversion

- install.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-531
remove-forgotten-condition for datadog
> PAAS-531: remove-forgotten-condition for datadog

- jahia/jahia_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-464
change tomcat logrotate parameters
> PAAS-464: change tomcat logrotate parameters

- jahia/jahia_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-519
secure cookies
> Paas 519: secure cookies

- jahia/jahia_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-598
increase maxHttpHeaderSize
> PAAS-598: increase maxHttpHeaderSize

- jahia/jahia_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-633
> Paas 633 manifest part of context.xml integration in jahia"s image

- install.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-599
> PAAS-599 remove useless proxysql action and event

- jahia/jahia_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-638
> PAAS-638 change the java version test because do not works anymore

- configs/502.http
- configs/haproxy-10-jahia.cfg
- haproxy/haproxy_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-636
haproxy maintenance page
> PAAS-636: add haproxy custom 502 page

- install.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-643
> PAAS-643: Set cloudlets for MariaDb nodes to 40 (both dev and prod)

- utils/rewrite-rules.yml
get rewrite rules feature and return old rewrites in case of asyntax error
> PAAS-401: rewrite rules

- configs/haproxy-00-global.cfg
JIRA issue: https://jira.jahia.org/browse/PAAS-403
set auth basic realm name
exclude tools from auth basic
> Paas 403 auth basic

- install.yml
- update.yml
- utils/manage-auth-basic.yml
- utils/rewrite-rules.yml
- utils/set-jahia-tools-password.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-651
remove baseurl
> Paas 651 remove baseurl

- utils/rewrite-rules.yml
update variable name to avoid parsing error on the front
> PAAS-401: update variable name to avoid parsing error on the front

- utils/set-jahia-tools-password.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-687
> PAAS-687 run yum with root user should be better

- onAfterClone.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-721
> Paas 721 fix datadog service clone

- scripts/set-rewrite-rules.py
- utils/rewrite-rules.yml
> Paas 401 haproxy rewrite rules

- common/common_actions.yml
- install.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-730
limit journald storage quotas to 200M
> PAAS-730: limit journald storage quotas to 200M

- utils/manage-auth-basic.yml
- utils/set-jahia-root-password.yml
- utils/set-jahia-tools-password.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-689
handle base64 password encoding in  jelastic package
> PAAS-689: handle base64 password encoding in  jelastic package

- install.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-728
lower xmx value
> PAAS-728: lower xmx value

- scripts/set-rewrite-rules.py
another fix encoding ...  back to utf-8
> PAAS-401: another fix encoding ...  back to utf-8

- onAfterClone.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-764
> PAAS-764: fixing clone when datadog not installed

- dx-upgrade.yml
- install.yml
- jahia/jahia_actions.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-716
Good luck for this review !
> Paas 716 handle rolling upgrades

- onAfterClone.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-691
Short description: update serverid after clone in jahia.node.properties
> PAAS-691: update serverid after clone in jahia.node.properties

- dx-upgrade.yml
- jahia/jahia_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-779
> PAAS-779 use restore-module-state for bulk upgrade

- dx-upgrade.yml
> PAAS-779 restore modules and states only if source >=7320

- dx-upgrade.yml
- haproxy/haproxy_actions.yml
- install.yml
- update.yml
stop/start/restart/redeploy and before upgrade
JIRA issue: https://jira.jahia.org/browse/PAAS-561
remove/add cp node in haproxy config at stop/start/restart/redeploy and before upgrade
> PAAS-561: remove/add cp node in haproxy config at

- configs/dd_agent_haproxy_conf.yml
- configs/rsyslog_haproxy
- haproxy/haproxy_actions.yml
- install.yml
- scripts/set_dd_tags.sh
JIRA issue: https://jira.jahia.org/browse/PAAS-372
add haproxy monitoring
> Paas 372 add haproxy monitoring

- configs/dd_agent_process_conf.yml
- haproxy/haproxy_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-372
add haproxy process monitor
> PAAS-372: add haproxy process monitor

- database/mariadb_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-848
> PAAS-848: Set buffer size on mariadb nodes

- jahia/jahia_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-347
add expandImportedFilesOnDisk to jahia.properties
> PAAS-347: add expandImportedFilesOnDisk to jahia.properties

- jahia/jahia_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-874
> PAAS-874 switch jdbc to sequential mode instead of loadbalance

- configs/dd_agent_tomcat_conf.yaml
- jahia/jahia_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-699
> Paas 699 group stacktraces for datadog

- jahia/jahia_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-910
> PAAS-910: remove loadbalance for jahia < 7.3

- database/galera_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-933
- Fix stopGalera method for dev env
> PAAS-933: fix stopGalera method for dev env mode

- database/galera_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-933
- Improve error handling on method stopGalera
> PAAS-933: improve error handling on method stopGalera

- database/galera_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-933
- fix variable accessibility
> PAAS-933: fix variable accessibility

- onAfterClone.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-951
- Fix reset JR_J_LOCAL_REVISIONS after a clone
> PAAS-951: Fix reset JR_J_LOCAL_REVISIONS after a clone

- install.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-943
- Upgrade haproxy to 2.1.4
> PAAS-943: Update haproxy tag to 2.1.4

- reset-polling.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-970
- Create a "reset-polling" package
> PAAS-970: Create a "reset-polling" package

- dx-upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-961
> PAAS-961: keep  jahia-unomi link after upgrade

- install.yml
- jahia/jahia_actions.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-914
> PAAS-914: saving JCR indices folders when redeploying

- jahia/jahia_actions.yml
JIRA issue: https://jira.jahia.org/browse/COPS-47
- Add cache configuration to jahia.properties
> COPS-47: Add jahia cache configuration

- haproxy/haproxy_actions.yml
- install.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-959
> PAAS-959: handling haproxy redeploy

- haproxy/haproxy_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-959
> PAAS-959: fixing permission mistake with last PR

- install.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-959
> PAAS-959: fixig oversight with haproxy onAfterRedeploy actions

- install.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-994
> PAAS-994: fix tag for mariadb docker image

- database/galera_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-995
- Improve code stopping galera
> PAAS-995: Improve code stopping galera

- database/mariadb_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-955
> PAAS-955: handle mariadb multilines logs in datadog conf.

- database/galera_actions.yml
- database/mariadb_actions.yml
- install.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-952
> PAAS-952: upgrading to mariadb 10.4.13

- README.md
JIRA issue: https://jira.jahia.org/browse/PAAS-1023
> PAAS-1023: adding README

- dx-upgrade.yml
- jahia/jahia_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1009
> PAAS-1009: fix jahia-unomi link

- dx-upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-904
> PAAS-904: add pre-formated comments for jahia upgrade

- configs/haproxy-00-global.cfg
JIRA issue: https://jira.jahia.org/browse/PAAS-1078
> PAAS-1078: protect /healthcheck from client custom rules

- database/mariadb_actions.yml
- haproxy/haproxy_actions.yml
- install.yml
- update.yml
for haproxy redeploy
JIRA issue: https://jira.jahia.org/browse/PAAS-1086
> PAAS-1086: Handle mariadb nodes redeploy and fix datadog setup

- haproxy/haproxy_actions.yml
- install.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1086
> PAAS-1086: Fix datadog setup after haproxy redeploy

- database/mariadb_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1093
> PAAS-1093: fix open_files limit for mysql process

- database/mariadb_actions.yml
> PAAS-1093: fix wrong bash expansion

- common/common_actions.yml
- database/galera_actions.yml
- database/mariadb_actions.yml
- haproxy/haproxy_actions.yml
- jahia/jahia_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1073
> Paas 1073 handle errors

- jahia/jahia_actions.yml
- utils/set-jahia-tools-password.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1131
> PAAS-1131: Set workaround for the $+ bug in clouscripting

- configs/haproxy-00-global.cfg
- configs/haproxy-11-proc.cfg
- haproxy/haproxy_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1123
> PAAS-1123: configure direct access to processing on haproxy

- dx-upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-927
- Move comment upgrade step 1 for polling
> PAAS-927: Move comment upgrade step 1 for polling

- onAfterClone.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-130
> COPS-130: fix galera setup after clone

- onAfterClone.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-130
> COPS-130: fix galera setup after clone (again)

- region_migrate.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1181
- manage region migration for jahia with eventuality of shared jcustomer
> PAAS-1181: dx region migration

- dx-upgrade.yml
- install.yml
- onAfterClone.yml
- reset-polling.yml
- update.yml
- utils/manage-auth-basic.yml
- utils/rewrite-rules.yml
- utils/set-jahia-root-password.yml
- utils/set-jahia-tools-password.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1213
> PAAS-1213: Homogenize packages metadata

- region_migrate.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1181
Improve indentation
remove trailing spaces
use ${globals.x} instead of "${global.x}"
> PAAS-1181: Fix condition mismatched variable

- onAfterClone.yml
master twice cause wsrep crash the first time
JIRA issue: https://jira.jahia.org/browse/PAAS-130
> COPS-130: fix galera setup after clone : fill grastate.dat and restart

- region_migrate.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1223
> PAAS-1223: Change 'targetRegion' setting name

- region_migrate.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1222
> PAAS-1222: Force shell blocks to fail together

- install.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1045
> PAAS-1045: disable direct node access

- database/mariadb_actions.yml
- haproxy/haproxy_actions.yml
- jahia/jahia_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1237
> PAAS-1237: fix permissions on jelastic packages log folder

- utils/restart-tomcat-nodes.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1265
> PAAS-1265: add package to rolling restart Tomcat nodes

- jahia/jahia_actions.yml
- onAfterClone.yml
JIRA issue: https://jira.jahia.org/browse/COPS-148
> COPS-148 change jahia's serverId to be {browsing,processing}.nodeid

- install.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1271
> PAAS-1271: generate token for jahia healtcheck

- haproxy/haproxy_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1257
> PAAS-1257: fix user executing the cmd to install jq package

- jahia/jahia-rolling-restart.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1265
> PAAS-1265: Move jahia-rolling-restart package

- utils/check_jexperience.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1304
> PAAS-1304: check jexperience and jcustomer configurations

- install.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1296
Create Vault envvars on haproxy nodes at env installation
> PASS-1296: Create Vault envvars on haproxy nodes

- utils/check_jexperience.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1304
> PAAS-1304: add error messages when jCustomer url or password is wrong

- configs/dd_agent_haproxy_conf.yml
- configs/logrotate_haproxy
- haproxy/haproxy_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1283
> PAAS-1283: fix haproxy logrotate and add haproxy status logs to datadog

- configs/haproxy-00-global.cfg
JIRA issue: https://jira.jahia.org/browse/PAAS-1282
Added HTTP Security Response Headers at HAProxy level
> PAAS-1282: Add security HTTP headers at HAProxy level

- utils/set-jahia-tools-password.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1230
> PAAS-1230: fix password update with dollar signs in base64 hash

- install.yml
> add underscores to vault env var

- configs/galera.cnf
JIRA issue: https://jira.jahia.org/browse/PAAS-1319
> PAAS-1319: define (bigger) galera cache size

- configs/haproxy-00-global.cfg
- scripts/haproxy-backend-healthcheck.sh
JIRA issue: https://jira.jahia.org/browse/PAAS-1308
> PAAS-1308: fix haproxy healthcheck path

- scripts/haproxy-backend-healthcheck.sh
JIRA issue: https://jira.jahia.org/browse/PAAS-1324
> PAAS-1324: allow YELLOW for haproxy healthcheck

- jahia/jahia_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1285
> PAAS-1285: use healthcheck module for startupJahiaHealthCheck action

- utils/rewrite-rules.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1170
> PAAS-1170: Use vault to fetch haproxy configurations

- utils/rewrite-rules.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1170
> PAAS-1170: Use vault to fetch haproxy configurations - more fixes

- migration-to-v2.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1207
> PAAS-1207: add Strongswan to Tomcat nodes

- migrations/migration-to-v2.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1207
> PAAS-1207: Fix migration-to-v2

- install.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1322
> PAAS-1322: Remove envLink on Jahia env deletion

- install.yml
- jahia/jahia_actions.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1322
> PAAS-1322: Remove envLink on Jahia env deletion - move action to Mixin

- common/common_actions.yml
- database/galera_actions.yml
- database/mariadb_actions.yml
- haproxy/haproxy_actions.yml
- install.yml
- jahia/jahia_actions.yml
- migrations/v2/migration-to-v2.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1336
> Paas 1336 improve migrations system

- database/galera_actions.yml
- database/mariadb_actions.yml
- haproxy/haproxy_actions.yml
- jahia/jahia_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1336
> PAAS-1336: fix healthchecks

- migrations/v2/migration-to-v2.yml
JIRA issue: https://jira.jahia.org/browse/COPS-244
> COPS-244: Fix vault URL envvar inmigration script

- jahia/jahia_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1366
> PAAS-1366: Remove org.apache.karaf.cellar.groups.cfg edition

- dx-upgrade.yml
- migrations/v3/migration-to-v3.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1342
> PAAS-1342: Fix NodeGroupData on cp group on Jahia env upgrade

- configs/haproxy-00-global.cfg
- migrations/v3/migration-to-v3.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1357
- Fix haproxy conf for Jahia and healthcheck.
- Update migration script.
> PAAS-1357: Fix haproxy conf for Jahia and healthcheck.

- migrations/v3/migration-to-v3.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1357
- Fix multiple line insertion problem in migration script
> PAAS-1357: Fix multiple line insertion problem in migration script

- dx-upgrade.yml
- haproxy/haproxy_actions.yml
- install.yml
- jahia/jahia-rolling-restart.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1368
> Paas 1368 handle haproxy pool

- common/common_actions.yml
- install.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1359
> PAAS-1359: remove onUninstall event

- jahia/jahia-upgrade-healthcheck.yml
- migrations/v3/migration-to-v3.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1317
> PAAS-1317: upgrade healthcheck

- install.yml
- migrations/v3/migration-to-v3.yml
- migrations/v3/strongswan_defaults
- migrations/v3/strongswan_logger
- migrations/v3/strongswan_logrotate
- migrations/v3/strongswan_override
- utils/ipsec.yml
> PAAS-1208 handle ipsec connection(s) with strongswan

- migrations/v3/migration-to-v3.yml
- utils/ipsec.yml
> PAAS-1208 fix a lot of stuff

- utils/ipsec.yml
> PAAS-1208 set nodegroupdata on cp with env's ipsec status

- install.yml
- jahia/jahia_actions.yml
- migrations/v3/migration-to-v3.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1369
> PAAS-1369: Fix Healthcheck Duration

- migrations/v3/migration-to-v3.yml
> PAAS-1208 fix typo

- migrations/v3/migration-to-v3.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1369
> PAAS-1369: Move addHealthcheckEnvVar action to be done first

- configs/haproxy-00-global.cfg
- migrations/v3/migration-to-v3.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1433
> PAAS-1433: increase client and server timeout

- utils/ipsec.yml
> PAAS-1208 better handle problem when talking to vault

- common/common_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1435
> PAAS-1435: Check env status before logging event

- database/proxysql_actions.yml
- install.yml
- migrations/v3/migration-to-v3.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1128
> PAAS-1128 Set up ProxySQL at Jahia environment installation

- database/proxysql_actions.yml
- region_migrate.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1128
> PAAS-1128 fix migration and remove useless actions

- migrations/v3/migration-to-v3.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1434
> PAAS-1434: Upgrade healthcheck module to 1.2.1 and 2.3.1

- install.yml
- jahia/jahia_actions.yml
- migrations/v3/migration-to-v3.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1457
Some actions are not useful anymore in migration v3 package since we redeploy tomcat nodes
> Paas 1457 update dx upgrade and migration v3

- dx-upgrade.yml
- install.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1455
> PAAS-1455: Fix Healthcheck on proc node during dx-upgrade

- migrations/v3/migration-to-v3.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1457
> PAAS-1457: restore upgrade healthcheck action

- migrations/v3/migration-to-v3.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1457
> PAAS-1457: add healthcheck_duration envvar as first step

- .github/CODEOWNERS
- README.md
- common/common_actions.yml
- database/mariadb_actions.yml
- dx-upgrade.yml
- haproxy/haproxy_actions.yml
- install.yml
- jahia/jahia_actions.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1383
Please merge at same time as https://github.com/Jahia/jahia-cloud-modules/pull/277
> PAAS-1383: Remove unused 'package type' notion

- dx-upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1442
> PAAS-1442: New upgrade patching process will only work starting from 7.3.8.0

- database/mariadb_actions.yml
- install.yml
- region_migrate.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1446
> PAAS-1446 Ensure mysql service is not started twice on redeployment

- dx-upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1442
> PAAS-1442: Fix variable name

- database/proxysql_actions.yml
- jahia/jahia_actions.yml
> disable proxysql custom checks if single galera

- configs/haproxy-00-global.cfg
- database/proxysql_actions.yml
- jahia/jahia_actions.yml
- migrations/v3/migration-to-v3.yml
> fix haproxy config migration

- jahia/jahia-upgrade-healthcheck.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1317
> PAAS-1317: fix jahia Healthcheck action

- migrations/v3/migration-to-v3.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1336
> PAAS-1336: secure Jahia redeploy for migration v3 script

- migrations/v3/resurect-env-after-failed-migration-to-v3.yml
> migration package for broken envs

- configs/dd_agent_process_conf.yml
- migrations/v4/migration-to-v4.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1465
> PAAS-1465: fix Datadog processes check for Haproxy

- migrations/v4/migration-to-v4.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1465
Taking the redirect into account
> PAAS-1465: fix migration v4 updateDatadogProcessCheck

- migrations/v3/replay-healthcheck-upgrade.yml
I couldn't create a dedicated ticket because Jira is down :x
> Replay healthcheck module upgrade after migration to v3

- install.yml
- jahia/jahia_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1472
> PAAS-1472: set imageMagickPath to /opt/magick/bin

- migrations/v3/fix-redeploy-conf.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1481
> PAAS-1481: add package to fix redeploy.conf after v3 release

- migrations/v3/fix-redeploy-conf-for-good.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1491
> PAAS-1491: Fix redeploy.conf (for good)

- jahia/jahia_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1458
> PAAS-1458 fix script block's indent

- utils/rewrite-rules.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1364
> PAAS-1364: add md5sum check on setrewriterules package

- install.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1500
> PAAS-1500: Remove useless settings from install

- install.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1500
> Paas 1500 fix settings

- utils/ipsec.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1503
> PAAS-1503: fix ipsec setup in case of auto=route parameter

- utils/ipsec.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1503
> PAAS-1503: fix strongswan up no working if new connection

- migrations/v4/migration-to-v4.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1453
> PAAS-1453: add JELASTIC_EXPOSE=0 env var

- configs/dd_agent_haproxy_conf.yml
- haproxy/haproxy_actions.yml
- jahia/jahia_actions.yml
- migrations/v4/migration-to-v4.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1479
> PAAS-1479: Add/fix datadog service tag for ipsec, proxysql and haproxy

- migrations/v4/migration-to-v4.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1507
> PAAS-1507: fix datadog user password

- migrations/v4/migration-to-v4.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1479
> PAAS-1479: Fix missing quote and restart datadog-agent

- install.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1495
> PAAS-1495: Add HN affinity for non-ES nodes

- migrations/v4/migration-to-v4.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1501
> PAAS-1501: migration script v4 -> create environments in papi

- configs/haproxy-10-jahia.cfg
- configs/haproxy-11-proc.cfg
JIRA issue: https://jira.jahia.org/browse/PAAS-1536
need to use /modules/healthcheck to avoid redirection issues
> PAAS-1536: Fix healthcheck URL

- migrations/v4/fixes.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1539
> PAAS-1539: add fixes for migration to v4
